### ISSUE TITLE
Site broken

### ISSUE THREAD

**Issue by atmos-o** [peeyush14goyal/AmazonPrime-ReactJS-Clone#1]
This is what I get when running stable and dev

![image](https://user-images.githubusercontent.com/44858581/117128130-ec877f00-ad94-11eb-816e-1f29dc9ad2b1.png)

**Comment by peeyush14goyal** [comment]
@atmos-o  Have you added your key for TMDB API? That field is empty in github code

**Comment by atmos-o** [comment]
Thansk, that fixed it

Searched `const api_key` in this repo and placed my API key inside `' '` for all instances of it.

**Comment by peeyush14goyal** [comment]
Great ✔
